### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bmaher** [zalando-incubator/zelt#5]
In order to understand how to use Zelt and how it works,
I need detailed documentation.

**Comment by bmaher** [comment]
The ReadTheDocs builds keep failing with the message:

```bash
Processing /home/docs/checkouts/readthedocs.org/user_builds/zelt/checkouts/latest
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/docs/checkouts/readthedocs.org/user_builds/zelt/envs/latest/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-tjd_9md0/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-tjd_9md0/
```
_https://readthedocs.org/projects/zelt/builds/9109143/_

I can't work out what's going on here, @thilp @tortila any ideas?

**Comment by thilp** [comment]
I recommend to wipe RTD's cache when faced with this kind of ridiculous error. I will do it tonight if @tortila doesn't beat me to it!

**Comment by bmaher** [comment]
👍 that worked, thanks.

**Comment by tortila** [comment]
Wiping the cache is actually somehow a recommended solution: https://docs.readthedocs.io/en/stable/guides/wipe-environment.html. I wonder if there's an option to not use caching at all, if it's so problematic with pip?
